- hosts: all
  become: true
  tasks:
          - name: install vsftpd
            apt:
                    name: vsftpd
                    state: present

            when: ansible_distribution == "Ubuntu" or "Redhat"
