## Install apache & change port

- hosts: all
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: copy index.html
      copy:
        content: "Welcome to webserver\n"
        dest: /var/www/html/index.html

    - name: Ensure the default Apache port is 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 8080

    - name: allow port 8080 into firewalld
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: true

    - name: start httpd
      service:
        name: apache2
        state: started
        enabled: true
 

