- name: Example of ansible vault
  hosts: all
  become: true
  vars:
    mypass: redhat

  tasks:
  - name: add new user
    user:
      name: shyam
      password: "{{ mypass | password_hash('sha512') }}"
