- name: Example of ansible vault
  hosts: all
  become: true
  vars_files:
          - crypt.yml

  tasks:
  - name: add new user
    user:
      name: shyam
      password: "{{ mypass | password_hash('sha512') }}"
