## Prompt variables

- hosts: all
  become: true
  vars_prompt:

          - name: username
            prompt: What is your username?
            private: no

          - name: password
            prompt: What is your password?
            private: yes

  tasks:
    - name: add user and apply password
      user:
              name: "{{ username }}"
              state: present
              password: "{{ password | password_hash('sha512')}}"
