- name: Example of playbook variable
  hosts: all
  become: true
  vars:
    web: apache2
    web_root: /var/www/html

  tasks:
    - name: install the package
      apt:
        name: "{{ web }}"
        state: present

    - name: start "{{ web }}"service 
      service:
        name: "{{ web }}"
        state: started

    - name: create document root "{{ web_root }}"
      file:
        path: "{{ web_root }}"
        state: directory

    - name: Copy Index.html page into "{{ web_root }}"
      copy:
        content: "Hello World\n"
        dest: "{{ web_root }}/index.html"

