- name: Example of simple loop
  hosts: all
  become: true
  tasks:
    - name: add user
      user:
        name: "{{ item }}"
        state: present
        password: "{{ item | password_hash('sha512') }}"
      loop: "{{ query('lines', 'cat user_list2.yml') }}"
