- name: Example of handlers
  hosts: all
  become: true
  tasks:
    - name: deploy application
      copy:
              content: 'Hello India'
              dest: /etc/abc.conf
      notify: 
        - webservice

  handlers:
           - name: restart_apache
             service: 
               name: apache2
               state: restarted
             listen: webservice

           - name: create file
             command: touch /tmp/abc.conf
             listen: webservice
